### ISSUE TITLE
Feature request: enabling read replica through Terraform

### ISSUE THREAD

**Issue by dennisameling** [timescale/terraform-provider-timescale#121]
Currently, this Terraform provider only supports setting up a HA replica. We'd love for it to support read replicas too, so filing this as a feature request.

<img width="1104" alt="image" src="https://github.com/timescale/terraform-provider-timescale/assets/17739158/038c8bfb-8fdf-4907-9f01-f1106c1a4ab6">

**Comment by alevy713** [comment]
Thanks for the feature request, read replicas are now supported in `v1.2.0`. [Here's](https://github.com/timescale/terraform-provider-timescale/blob/main/examples/resources/resource.tf#L8) an example using the new attribute. Hope that helps!
