### ISSUE TITLE
Feature Request: Enable Connection Pooling and Retrieve Pooler Hostname

### ISSUE THREAD

**Issue by shababq** [timescale/terraform-provider-timescale#142]
I'm using the TimescaleDB Terraform provider and noticed it doesn't support enabling connection pooling or retrieving the pooler hostname.

This feature is crucial for my application's performance and ease of connection. Currently, I'm manually constructing the pooler hostname, which isn't ideal.

I request a feature to enable connection pooling and retrieve the pooler hostname directly from the TimescaleDB service resource.

Thank you for considering this request.

Best, 
Shabab Qaisar

**Comment by Khyme** [comment]
Implementing for datasource here https://github.com/timescale/terraform-provider-timescale/pull/145 , if that helps.

Resource is next.

**Comment by Khyme** [comment]
Supported in v1.4.0

**Comment by shababq** [comment]
@Khyme 
here is my code snippet and i am getting null value for pooler_hostanme
```resource "timescale_service" "service" {
  name  = var.timescale_instance

  enable_ha_replica = false
  memory_gb         = var.memory_gb
  milli_cpu         = var.milli_cpu
  region_code       = var.aws_region
  vpc_id            = var.vpc_id
  connection_pooler_enabled = true

  lifecycle {
    create_before_destroy = true
    prevent_destroy       = true
  }
}

`output "timescale_service_host" {
  value = timescale_service.service.pooler_hostname
}`
here is my lock file that shows i have installed recommended  version
1.4.1

```
provider "registry.terraform.io/timescale/timescale" {
  version     = "1.4.1"
  constraints = "1.4.1"
  hashes = [
    "h1:I6VRqyzGgFGfHtTV2VG3bLNNZJ7XqQ10LxiHS/drxTQ=",
    "zh:3593cc6c9c51ec16695938bc81e68dfda32745313a078c27d1874ec3af7d9dcd",
    "zh:4517fd513047ccc8368ebc3b5424a37035b0c640c966877edf0a1784929b10ac",
    "zh:59da3298a51a4be47203bc8bb42d6cf4c1a9b6a4b6a0b9c1350fc1fdd8f1d853",
    "zh:631fec6bb5cd40e1d19da84843adabd19a0a06aea3821437f20c061f5a92a15b",
    "zh:68855ebed7076f897a2c5e60bb6697b139b0570205f336d7902478629df71448",
    "zh:74754299e98c8d7892c4f804202d5f7f560cfcb5f4a34f8d9df71828afbc3a74",
    "zh:861b4568541c08d96d0f75a9ed71b88b28cf86584cd08b064f9c290f3c86541e",
    "zh:890df766e9b839623b1f0437355032a3c006226a6c200cd911e15ee1a9014e9f",
    "zh:8ec8364240c19d2b66d6312a7fd9af122c7293c0ea58bc05485e169c7f39e0c4",
    "zh:8f7a925cee15aa6287f7cbe805bf7805f19371f4d55ee9faf551177dd6ff2ed2",
    "zh:ad3b96ecef9b2df83656366e0aa79bc7614156edfa538fb6c29006a89a523e54",
    "zh:be80e4856f018da75d76332c74e202f31766214822787fcb169f9aa8230d7ca2",
    "zh:c1043ca729cedcda3f646b77d930c6c54d941b29c4ad184e49e7d2c915849132",
    "zh:ca2c0f451d14c285b83d4fb9d8e338aa05583c6b135be1b1ac92b02715f66ee5",
    "zh:d8290b0cad6be1a1f24830a820c7c08d3d844e030c22948a7a4daf9121e2d475",
  ]
}

```
