### ISSUE TITLE
VPC peering connection returns incorrect ID

### ISSUE THREAD

**Issue by jkrall** [timescale/terraform-provider-timescale#158]
(possibly related to https://github.com/timescale/terraform-provider-timescale/issues/131)

Having manually setup a peering-connection in the timescale UI, I am getting the following data from terraform in the `peering_connections` array:

```
            "peering_connections": [
              {
                "error_message": "",
                "id": 3011,
                "peer_vpc": {
                  "account_id": "...hidden...",
                  "cidr": "172.16.0.0/16",
                  "id": "...hidden...",
                  "region_code": "us-east-2"
                },
                "status": "ACTIVE",
                "vpc_id": "...hidden..."
              }
            ],
```

Note that the `id` being returned is a numeric number, rather than the AWS id of the peering connection, ala `pcx-...`

This prevents using terraform to reference the peering connection and configure an `aws_route` to refer to the peering connection.

**Comment by Khyme** [comment]
Fixed with version v1.9.0 !
