### ISSUE TITLE
Feature request: Whitelists

### ISSUE THREAD

**Issue by a-nldisr** [timescale/terraform-provider-timescale#84]
Feature request:
- Add the ability to manage whitelists on timescale through terraform.

**Comment by heilaschaefer** [comment]
@a-nldisr for your allow list, do you mean WRT from where timescale will accept TC connections ? or is this something internal to the DB ?

**Comment by a-nldisr** [comment]
Its in the managed Timescale instance interface, 
![image](https://github.com/timescale/terraform-provider-timescale/assets/1867776/6515ae28-9879-4776-8fd7-893bbba09cf8)

**Comment by Khyme** [comment]
Sorry for the late reply.
This provider only works for [Timescale cloud](https://console.cloud.timescale.com/) solution and not managed Timescale.

**Comment by a-nldisr** [comment]
@Khyme Timescale cloud does offer this feature?

> Sorry for the late reply. This provider only works for [Timescale cloud](https://console.cloud.timescale.com/) solution and not managed Timescale.

Great to hear that this feature is present when Timescale offers Cloud offerings in the region we are required to run our services at due to regulations!

**Comment by mfreed** [comment]
Hi @a-nldisr Supporting IP allow lists is on the roadmap for Timescale Cloud, although don't yet have a firm delivery date.   Even without, connections to your database are all encrypted in "strict SSL" mode with fully verifiable (non-self-signed) certificate chains.

That said, most of our security-conscious customers today utilize its support for VPC Peering, so ensure that traffic never transverses public IP space:  https://docs.timescale.com/use-timescale/latest/vpc/
