### ISSUE TITLE
Timescale services inside VPC have blank hostname

### ISSUE THREAD

**Issue by nostromoJohn** [timescale/terraform-provider-timescale#89]
Version: 0.3.0

Description of this issue:
When accessing read-only attributes for the timescale service, services inside a VPC return a blank hostname and wrong port.

How to reproduce:
After creating a timescale service with Terraform, attach it to a VPC through Timescale Cloud (This is currently not possible using Terraform.)
Access the [hostname](https://registry.terraform.io/providers/timescale/timescale/latest/docs/resources/service#hostname) and [port](https://registry.terraform.io/providers/timescale/timescale/latest/docs/resources/service#port) attributes for the given service - they are either empty or wrong.

Expected behavior: Hostname and port update after attaching service to VPC as they do in Timescale Cloud's UI.

**Comment by Khyme** [comment]
Hello @nostromoJohn ,
Thank you for your feedback. v0.3.1 should fix this issue and read hostname and port correctly in case there is a VPC attached to the service.
